stages:
  - build

default:
  image: images.paas.redhat.com/it-cloud-ocp-registry-redhat-io-proxy/ubi9/go-toolset:1.25
  tags:
    - itup-alm-x86

build-clusters:
  stage: build
  script:
    - git config --global --add safe.directory "$PWD"
    - go mod download
    - go install github.com/magefile/mage@latest
    - rm -rf resources/clusters/ && $(go env GOPATH)/bin/mage build:clusters
    - if [ -n "$(git status --porcelain)" ]; then git status && git diff && false; fi
  variables:
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_MEMORY_LIMIT: "4Gi"
