stages:
  - build

default:
  image: images.paas.redhat.com/it-cloud-ocp-registry-redhat-io-proxy/ubi9/go-toolset:1.25
  tags:
    - itup-alm-x86

go-lint:
  stage: build
  script:
    - git config --global --add safe.directory "$PWD"
    - go mod download
    - make go-lint
  variables:
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_MEMORY_LIMIT: "4Gi"

clusters:
  stage: build
  script:
    - git config --global --add safe.directory "$PWD"
    - go mod download
    - go install github.com/magefile/mage@latest
    - rm -rf resources/clusters/ && $(go env GOPATH)/bin/mage build:clusters
    - rm -rf resources/o11y && $(go env GOPATH)/bin/mage build:sloRules && $(go env GOPATH)/bin/mage build:rules
    - if [ -n "$(git status --porcelain)" ]; then git status && git diff && false; fi
  variables:
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_MEMORY_LIMIT: "4Gi"

yaml-lint:
  stage: build
  script:
    - git config --global --add safe.directory "$PWD"
    - go mod download
    - make yaml-lint
  variables:
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_MEMORY_LIMIT: "1Gi"

rules:
  stage: build
  script:
    - git config --global --add safe.directory "$PWD"
    - make all
    - if [ -n "$(git status --porcelain)" ]; then git status && git diff && false; fi
  variables:
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_MEMORY_LIMIT: "2Gi"
