module _ // Manually maintained for Loki; bingo get cannot resolve Loki's local replace directives here.

// Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

// Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

// Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

// Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.25.7

replace github.com/Azure/azure-sdk-for-go => github.com/Azure/azure-sdk-for-go v68.0.0+incompatible

replace github.com/Azure/azure-storage-blob-go => github.com/MasslessParticle/azure-storage-blob-go v0.14.1-0.20240322194317-344980fda573

replace github.com/gocql/gocql => github.com/grafana/gocql v0.0.0-20200605141915-ba5dc39ece85

replace github.com/hashicorp/memberlist => github.com/grafana/memberlist v0.3.1-0.20251126142931-6f9f62ab6f86

replace github.com/grafana/regexp => github.com/grafana/regexp v0.0.0-20240518133315-a468a5bfb3bc

replace github.com/grafana/loki/pkg/push => github.com/grafana/loki/pkg/push v0.0.0-20250630054201-94c0ba7b0952

replace github.com/influxdata/go-syslog/v3 => github.com/leodido/go-syslog/v4 v4.3.0

replace github.com/thanos-io/objstore => github.com/grafana/objstore v0.0.0-20250728171719-b5d3b766d1b0

exclude k8s.io/client-go v8.0.0+incompatible

require github.com/grafana/loki/v3 v3.7.0 // cmd/logcli
