# Generate hcp-loki-alerting-rules.yaml from split domain files in hcp-loki-rules/alerts/
# This script combines all split Template files into a single template (like generate-hcp-rules.sh).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HCP_LOKI_ALERTS_DIR="${SCRIPT_DIR}/../resources/tenant-rules/hcp-loki-rules/alerts"
OUTPUT_FILE="${SCRIPT_DIR}/../resources/tenant-rules/hcp-loki-alerting-rules.yaml"

YQ=${YQ:-yq}
# Check if "$YQ" is available
if ! command -v "$YQ" &> /dev/null; then
    echo "Error: $YQ is required but not installed." >&2
    exit 1
fi

# Define the order of files to process (controls order in output)
FILES=(
    "observability.yaml"
)

# Create temporary files
TEMP_OBJECTS=$(mktemp)
trap "rm -f $TEMP_OBJECTS" EXIT

# Collect all objects from all files into a JSON array
echo "[]" > "$TEMP_OBJECTS"

for file in "${FILES[@]}"; do
    filepath="${HCP_LOKI_ALERTS_DIR}/${file}"
    if [[ -f "$filepath" ]]; then
        # Extract objects array and append to our collection
        "$YQ" eval -o=json '.objects' "$filepath" > /tmp/current_objects.json
        "$YQ" eval-all -o=json '. as $item ireduce ([]; . + $item)' "$TEMP_OBJECTS" /tmp/current_objects.json > /tmp/merged.json
        mv /tmp/merged.json "$TEMP_OBJECTS"
    else
        echo "Warning: ${filepath} not found, skipping" >&2
    fi
done

# Build the final template with auto-generated warning
cat > "$OUTPUT_FILE" << 'HEADER'
# ============================================================================
# WARNING: This file is auto-generated from resources/tenant-rules/hcp-loki-rules/alerts/*.yaml
# DO NOT EDIT THIS FILE DIRECTLY!
#
# To modify HCP Loki alerting rules:
#   1. Edit the appropriate file in resources/tenant-rules/hcp-loki-rules/alerts/
#   2. Run: make hcp-loki-rules
#   3. Commit both the source file and this generated file
#
# Source files:
#   - hcp-loki-rules/alerts/observability.yaml (watchdog, Loki AlertingRules)
#
# Add new files to the FILES array in scripts/generate-hcp-loki-rules.sh
# ============================================================================
HEADER

"$YQ" eval -n '{
  "apiVersion": "template.openshift.io/v1",
  "kind": "Template",
  "metadata": {
    "name": "rhobs-hcp-loki-alerting-rules",
    "annotations": {
      "description": "Template for deploying HCP Loki AlertingRules to RHOBS"
    }
  },
  "parameters": [
    {"name": "NAMESPACE", "description": "Namespace to deploy the rules to", "required": true},
    {"name": "TENANT", "description": "Loki tenant ID for rule evaluation", "required": true},
    {"name": "REGION", "description": "Region where the RHOBS cell is deployed", "required": false, "value": ".+"},
    {"name": "ENVIRONMENT", "description": "Environment where the RHOBS cell is deployed", "required": false, "value": ".+"}
  ]
}' >> "$OUTPUT_FILE"

# Add the objects array
"$YQ" eval -i ".objects = $(cat $TEMP_OBJECTS)" "$OUTPUT_FILE"

echo "Generated ${OUTPUT_FILE}"
