#!/bin/bash
# Generate hcp-loki-recording-rules.yaml from split domain files in hcp-loki-rules/rules/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HCP_LOKI_RULES_DIR="${SCRIPT_DIR}/../resources/tenant-rules/hcp-loki-rules/rules"
OUTPUT_FILE="${SCRIPT_DIR}/../resources/tenant-rules/hcp-loki-recording-rules.yaml"

YQ=${YQ:-yq}
if ! command -v "$YQ" &> /dev/null; then
    echo "Error: $YQ is required but not installed." >&2
    exit 1
fi

FILES=(
    "cluster-provisioning.yaml"
)

TEMP_OBJECTS=$(mktemp)
trap "rm -f $TEMP_OBJECTS" EXIT

echo "[]" > "$TEMP_OBJECTS"

for file in "${FILES[@]}"; do
    filepath="${HCP_LOKI_RULES_DIR}/${file}"
    if [[ -f "$filepath" ]]; then
        "$YQ" eval -o=json '.objects' "$filepath" > /tmp/current_objects.json
        "$YQ" eval-all -o=json '. as $item ireduce ([]; . + $item)' "$TEMP_OBJECTS" /tmp/current_objects.json > /tmp/merged.json
        mv /tmp/merged.json "$TEMP_OBJECTS"
    else
        echo "Warning: ${filepath} not found, skipping" >&2
    fi
done

cat > "$OUTPUT_FILE" << 'HEADER'
# ============================================================================
# WARNING: This file is auto-generated from resources/tenant-rules/hcp-loki-rules/rules/*.yaml
# DO NOT EDIT THIS FILE DIRECTLY!
#
# To modify HCP Loki recording rules:
#   1. Edit the appropriate file in resources/tenant-rules/hcp-loki-rules/rules/
#   2. Run: make hcp-loki-recording-rules
#   3. Commit both the source file and this generated file
#
# Source files:
#   - hcp-loki-rules/rules/cluster-provisioning.yaml (provisioning IT event counts)
#
# Add new files to the FILES array in scripts/generate-hcp-loki-recording-rules.sh
# ============================================================================
HEADER

"$YQ" eval -n '{
  "apiVersion": "template.openshift.io/v1",
  "kind": "Template",
  "metadata": {
    "name": "rhobs-hcp-loki-recording-rules",
    "annotations": {
      "description": "Template for deploying HCP Loki RecordingRules to RHOBS"
    }
  },
  "parameters": [
    {"name": "NAMESPACE", "description": "Namespace to deploy the rules to", "required": true},
    {"name": "TENANT", "description": "Loki tenant ID for rule evaluation", "required": true},
    {"name": "REGION", "description": "Region where the RHOBS cell is deployed", "required": false, "value": ".+"},
    {"name": "ENVIRONMENT", "description": "Environment where the RHOBS cell is deployed", "required": false, "value": ".+"}
  ]
}' >> "$OUTPUT_FILE"

"$YQ" eval -i ".objects = $(cat $TEMP_OBJECTS)" "$OUTPUT_FILE"

echo "Generated ${OUTPUT_FILE}"
