package main

import (
	"github.com/thanos-community/thanos-operator/config"
	"gitlab.cee.redhat.com/rhobs/configuration/clusters"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

const (
	// thanosOperatorCRDRef is the commit ref used to sync the Thanos Operator CRDs from upstream thanos community repo.
	// This is generated by mage konflux:sync thanos-operator {ref} and should not be modified manually in normal circumstances.
	thanosOperatorCRDRef = "9a51474e391bdba2a497eee1ecd1833ec7fc40c4"
)

func operatorResources(namespace string, m clusters.TemplateMaps) ([]runtime.Object, error) {
	const (
		// thanosOperatorRBACBase is the base URL for fetching RBAC resources from upstream.
		thanosOperatorRBACBase = "https://raw.githubusercontent.com/thanos-community/thanos-operator/" + thanosOperatorCRDRef + "/config/rbac/"
	)
	config.SetGlobalPrefix("thanos-operator-")
	config.SetGlobalNamespace(namespace)
	config.SetGlobalCommonLabels("thanos-operator", "thanos-operator", "rhobs")
	config.SetGlobalManagerImage(clusters.TemplateFn(clusters.ThanosOperator, m.Images))

	deployment := config.ControllerManagerDeployment(config.WithPrometheusRule())

	for i, container := range deployment.Spec.Template.Spec.Containers {
		if container.Name == "manager" {
			deployment.Spec.Template.Spec.Containers[i].Resources = clusters.TemplateFn(clusters.Manager, m.ResourceRequirements)

			// Replace HTTPS metrics args with HTTP ones
			args := deployment.Spec.Template.Spec.Containers[i].Args
			var newArgs []string
			for _, arg := range args {
				// Skip the HTTPS metrics arguments
				if arg == "--metrics-secure" ||
					arg == "--metrics-bind-address=:8443" {
					continue
				}
				// Replace health probe address to avoid duplicates
				if arg == "--health-probe-bind-address=:8081" {
					continue
				}
				newArgs = append(newArgs, arg)
			}
			// Add HTTP metrics and health probe addresses
			newArgs = append(newArgs,
				"--metrics-bind-address=:8080",
				"--health-probe-bind-address=:8081",
			)
			deployment.Spec.Template.Spec.Containers[i].Args = newArgs

			// Add HTTP metrics port
			deployment.Spec.Template.Spec.Containers[i].Ports = []corev1.ContainerPort{
				{
					Name:          "http-metrics",
					ContainerPort: 8080,
					Protocol:      corev1.ProtocolTCP,
				},
			}

			// Add CONFIG_RELOADER_IMAGE environment variable
			deployment.Spec.Template.Spec.Containers[i].Env = []corev1.EnvVar{
				{
					Name:  "CONFIG_RELOADER_IMAGE",
					Value: clusters.TemplateFn(clusters.ConfigReloader, m.Images),
				},
			}
		}
	}

	// Fetch Manager ClusterRole from upstream
	managerRole, err := getClusterRole(thanosOperatorRBACBase + "role.yaml")
	if err != nil {
		return nil, err
	}
	// Override name and labels for our deployment
	managerRole.Name = "thanos-operator-manager-role"
	managerRole.Labels = map[string]string{
		"app.kubernetes.io/component":                  "rbac",
		"app.kubernetes.io/created-by":                 "thanos-operator",
		"app.kubernetes.io/instance":                   "manager-role",
		"app.kubernetes.io/managed-by":                 "rhobs",
		"app.kubernetes.io/name":                       "clusterrole",
		"app.kubernetes.io/part-of":                    "thanos-operator",
		"rbac.authorization.k8s.io/aggregate-to-admin": "true",
	}

	objs := []runtime.Object{
		deployment,
		managerRole,
		config.ManagerServiceAccount(),
		config.LeaderElectionRole(),
		config.LeaderElectionRoleBinding(),
		config.ManagerClusterRoleBinding(),
	}

	for _, crd := range config.CRDList {
		viewer := config.CRDViewerClusterRole(crd)
		viewer.Labels["rbac.authorization.k8s.io/aggregate-to-view"] = "true"
		objs = append(objs, viewer)
		editor := config.CRDEditorClusterRole(crd)
		editor.Labels["rbac.authorization.k8s.io/aggregate-to-edit"] = "true"
		objs = append(objs, editor)
	}

	service := &corev1.Service{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "Service",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "thanos-operator-controller-manager-metrics-service",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/component":  "metrics",
				"app.kubernetes.io/created-by": "thanos-operator",
				"app.kubernetes.io/instance":   "controller-manager-metrics-service",
				"app.kubernetes.io/managed-by": "rhobs",
				"app.kubernetes.io/name":       "service",
				"app.kubernetes.io/part-of":    "thanos-operator",
				"control-plane":                "controller-manager",
			},
		},
		Spec: corev1.ServiceSpec{
			Ports: []corev1.ServicePort{
				{
					Name:       "http-metrics",
					Port:       8080,
					Protocol:   corev1.ProtocolTCP,
					TargetPort: intstr.FromString("http-metrics"),
				},
			},
			Selector: map[string]string{
				"control-plane": "controller-manager",
			},
		},
	}

	objs = append(objs, service)

	return objs, nil
}
