package main

import (
	"github.com/thanos-community/thanos-operator/config"
	"gitlab.cee.redhat.com/rhobs/configuration/clusters"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/utils/ptr"
)

const (
	// thanosOperatorCRDRef is the commit ref used to sync the Thanos Operator CRDs from upstream thanos community repo.
	// This is generated by mage sync:operator and should not be modified manually in normal circumstances.
	thanosOperatorCRDRef = "702795686454e85760c0768f3c44feed00f82444"
)

func operatorResources(namespace string, m clusters.TemplateMaps) ([]runtime.Object, error) {
	const (
		// thanosOperatorRBACBase is the base URL for fetching RBAC resources from upstream.
		thanosOperatorRBACBase = "https://raw.githubusercontent.com/thanos-community/thanos-operator/" + thanosOperatorCRDRef + "/config/rbac/"
	)
	config.SetGlobalPrefix("thanos-operator-")
	config.SetGlobalNamespace(namespace)
	config.SetGlobalCommonLabels("thanos-operator", "thanos-operator", "rhobs")
	config.SetGlobalManagerImage(clusters.TemplateFn(clusters.ThanosOperator, m.Images))

	deployment := config.ControllerManagerDeployment(config.WithPrometheusRule())
	deployment.Spec.Template.Spec.Volumes = []corev1.Volume{
		{
			Name: "tls",
			VolumeSource: corev1.VolumeSource{
				Secret: &corev1.SecretVolumeSource{
					SecretName:  "kube-rbac-proxy-tls",
					DefaultMode: ptr.To(int32(420)),
					Optional:    ptr.To(false),
				},
			},
		},
		{
			Name: "service-ca",
			VolumeSource: corev1.VolumeSource{
				ConfigMap: &corev1.ConfigMapVolumeSource{
					LocalObjectReference: corev1.LocalObjectReference{
						Name: "openshift-service-ca.crt",
					},
					DefaultMode: ptr.To(int32(420)),
					Optional:    ptr.To(false),
				},
			},
		},
		{
			Name: "config",
			VolumeSource: corev1.VolumeSource{
				ConfigMap: &corev1.ConfigMapVolumeSource{
					LocalObjectReference: corev1.LocalObjectReference{
						Name: "thanos-operator-rbac-config",
					},
					DefaultMode: ptr.To(int32(420)),
					Optional:    ptr.To(false),
				},
			},
		},
	}

	for i, container := range deployment.Spec.Template.Spec.Containers {
		if container.Name == "manager" {
			deployment.Spec.Template.Spec.Containers[i].Resources = clusters.TemplateFn(clusters.Manager, m.ResourceRequirements)
			deployment.Spec.Template.Spec.Containers[i].VolumeMounts = []corev1.VolumeMount{
				{
					Name:      "tls",
					MountPath: "/etc/tls/private",
					ReadOnly:  true,
				},
				{
					Name:      "service-ca",
					MountPath: "/etc/service-ca",
					ReadOnly:  true,
				},
			}

			deployment.Spec.Template.Spec.Containers[i].Args = append(deployment.Spec.Template.Spec.Containers[i].Args,
				"--metrics-cert-path=/etc/tls/private",
				"--metrics-cert-name=tls.crt",
				"--metrics-cert-key=tls.key",
				"--metrics-client-ca-file=/etc/service-ca/service-ca.crt",
			)

			// deployment.Spec.Template.Spec.Containers[i].Env = []corev1.EnvVar{
			// 	{
			// 		Name:  "CONFIG_RELOADER_IMAGE",
			// 		Value: clusters.TemplateFn(clusters.ConfigReloader, m.Images),
			// 	},
			// }
		}
	}

	// Fetch Manager ClusterRole from upstream
	managerRole, err := getClusterRole(thanosOperatorRBACBase + "role.yaml")
	if err != nil {
		return nil, err
	}
	// Override name and labels for our deployment
	managerRole.Name = "thanos-operator-manager-role"
	managerRole.Labels = map[string]string{
		"app.kubernetes.io/component":                  "rbac",
		"app.kubernetes.io/created-by":                 "thanos-operator",
		"app.kubernetes.io/instance":                   "manager-role",
		"app.kubernetes.io/managed-by":                 "rhobs",
		"app.kubernetes.io/name":                       "clusterrole",
		"app.kubernetes.io/part-of":                    "thanos-operator",
		"rbac.authorization.k8s.io/aggregate-to-admin": "true",
	}

	objs := []runtime.Object{
		deployment,
		managerRole,
		config.ManagerServiceAccount(),
		config.LeaderElectionRole(),
		config.MetricsAuthClusterRole(),
		config.LeaderElectionRoleBinding(),
		config.ManagerClusterRoleBinding(),
		config.MetricsAuthClusterRoleBinding(),
	}
	for _, cm := range operatorServingCertConfigMaps(namespace) {
		objs = append(objs, cm)
	}

	for _, crd := range config.CRDList {
		viewer := config.CRDViewerClusterRole(crd)
		viewer.Labels["rbac.authorization.k8s.io/aggregate-to-view"] = "true"
		objs = append(objs, viewer)
		editor := config.CRDEditorClusterRole(crd)
		editor.Labels["rbac.authorization.k8s.io/aggregate-to-edit"] = "true"
		objs = append(objs, editor)
	}

	metricsReader := config.MetricsReaderClusterRole()
	metricsReader.Labels["rbac.authorization.k8s.io/aggregate-to-view"] = "true"
	objs = append(objs, metricsReader)

	service := config.MetricsService()
	service.Annotations = map[string]string{
		"service.beta.openshift.io/serving-cert-secret-name": "kube-rbac-proxy-tls",
	}
	objs = append(objs, service)

	return objs, nil
}

func operatorServingCertConfigMaps(namespace string) []*corev1.ConfigMap {
	labels := map[string]string{
		"app.kubernetes.io/component":  "manager",
		"app.kubernetes.io/created-by": "thanos-operator",
		"app.kubernetes.io/instance":   "controller-manager",
		"app.kubernetes.io/managed-by": "rhobs",
		"app.kubernetes.io/name":       "configmap",
		"app.kubernetes.io/part-of":    "thanos-operator",
	}

	serviceCert := &corev1.ConfigMap{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "ConfigMap",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "thanos-operator-serving-cert",
			Namespace: namespace,
			Labels:    labels,
			Annotations: map[string]string{
				"service.beta.openshift.io/inject-cabundle": "true",
			},
		},
		Data: map[string]string{},
	}

	rbacConfig := &corev1.ConfigMap{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "ConfigMap",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "thanos-operator-rbac-config",
			Namespace: namespace,
			Labels:    labels,
		},
		Data: map[string]string{
			"config.yaml": `"authorization":
  "static":
  - "path": "/metrics"
    "resourceRequest": false
    "user":
      "name": "system:serviceaccount:openshift-customer-monitoring:prometheus-k8s"
    "verb": "get"`,
		},
	}
	return []*corev1.ConfigMap{serviceCert, rbacConfig}
}
